import React, { useState, useEffect } from 'react';
import Navbar from '../../Component/Website/Header/Navbar';
import { Helmet } from "react-helmet";

const AIChecker = () => {
    const [textInput, setTextInput] = useState('');
    const [analysisResult, setAnalysisResult] = useState(null);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [activeTab, setActiveTab] = useState('story');

    // Mock analysis function - in a real app, this would connect to an API
    const analyzeText = () => {
        setIsAnalyzing(true);

        // Simulate API call delay
        setTimeout(() => {
            // Simple detection logic (for demonstration only)
            const aiPatterns = [
                'furthermore', 'moreover', 'it is important to note',
                'in conclusion', 'additionally', 'as a result'
            ];

            const aiWordCount = aiPatterns.filter(word =>
                textInput.toLowerCase().includes(word)
            ).length;

            const wordCount = textInput.split(/\s+/).length;
            const aiProbability = Math.min(0.95, (aiWordCount / 5) + (wordCount > 100 ? 0.2 : 0));
            const isHuman = Math.random() > aiProbability;

            setAnalysisResult({
                label: isHuman ? 'human' : 'AI-generated',
                score: isHuman ? (0.85 + Math.random() * 0.14).toFixed(2) : (0.92 + Math.random() * 0.07).toFixed(2),
                patternsDetected: aiWordCount,
                wordCount,
                entropy: (3.5 + Math.random() * 0.5).toFixed(2)
            });
            setIsAnalyzing(false);
        }, 1500);
    };

    return (

        <>


            <Helmet>
                {/* Primary Meta Tags */}
                <title>AI Checker: Exposing the Secrets Behind Human vs Machine Text</title>
                <meta
                    name="description"
                    content="Discover the ultimate AI Checker — the powerful tool that reveals whether text is written by a human or generated by AI. Stay ahead in the digital age, protect originality, and uncover hidden patterns in content like never before."
                />
                <meta name="keywords" content="AI Checker, detect AI text, human vs AI, AI detection tool, AI content verification, machine vs human writing" />
                <meta name="robots" content="index, follow" />

                {/* Open Graph / Facebook */}
                <meta property="og:type" content="website" />
                <meta property="og:title" content="AI Checker: Exposing the Secrets Behind Human vs Machine Text" />
                <meta
                    property="og:description"
                    content="Discover the ultimate AI Checker — the powerful tool that reveals whether text is written by a human or generated by AI. Stay ahead in the digital age, protect originality, and uncover hidden patterns in content like never before."
                />
                <meta property="og:image" content={`${process.env.PUBLIC_URL}/images/ai-checker-cover.jpg`} />
                <meta property="og:url" content="https://fyrexia.co.uk/ai-checker" />
                <meta property="og:image" content="https://i.postimg.cc/fRBN0c92/Capture-d-cran-2025-08-14-235925.png" />

                {/* Twitter */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content="AI Checker: Exposing the Secrets Behind Human vs Machine Text" />
                <meta
                    name="twitter:description"
                    content="Discover the ultimate AI Checker — the powerful tool that reveals whether text is written by a human or generated by AI. Stay ahead in the digital age, protect originality, and uncover hidden patterns in content like never before."
                />
                <meta name="twitter:image" content="https://i.postimg.cc/fRBN0c92/Capture-d-cran-2025-08-14-235925.png" />

            </Helmet>
            <Navbar></Navbar>


            <div className="min-h-screen bg-gradient-to-br from-blue-50 to-white py-12 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto">
                    <header className="text-center mb-16">
                        <div className="flex items-center justify-center mb-6">
                            <div className="bg-blue-600 w-16 h-16 rounded-xl flex items-center justify-center mr-4 shadow-lg">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" viewBox="0 0 20 20" fill="currentColor">
                                    <path fillRule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 01-2 0V6H3a1 1 0 010-2h1V3a1 1 0 011-1zm0 10a1 1 0 011 1v1h1a1 1 0 110 2H6v1a1 1 0 11-2 0v-1H3a1 1 0 110-2h1v-1a1 1 0 011-1zM12 2a1 1 0 01.967.744L14.146 7.2 13.047 14.01c-.04.3-.2.575-.45.75a1.1 1.1 0 01-.847.2l-5.4-1.1a1 1 0 01-.39-.18 1.1 1.1 0 01-.3-.45L5.854 7.2 7.033 2.744A1 1 0 018 2h4zm-2 4a1 1 0 00-1 1v5a1 1 0 002 0V7a1 1 0 00-1-1zm2 9a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
                                </svg>
                            </div>
                            <h1 className="text-4xl font-bold text-gray-900">AI Checker</h1>
                        </div>
                        <h2 className="text-xl text-blue-600 font-medium">Guardian of Digital Truth</h2>
                        <div className="h-1 w-32 bg-gradient-to-r from-blue-400 to-blue-600 mx-auto mt-4 rounded-full"></div>
                    </header>

                    <div className="bg-white rounded-2xl shadow-xl overflow-hidden mb-16">
                        <div className="border-b border-gray-200">
                            <nav className="flex">
                                <button
                                    className={`py-4 px-6 text-center flex-1 ${activeTab === 'story' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-600 hover:text-blue-500'}`}
                                    onClick={() => setActiveTab('story')}
                                >
                                    The Story
                                </button>
                                <button
                                    className={`py-4 px-6 text-center flex-1 ${activeTab === 'demo' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-600 hover:text-blue-500'}`}
                                    onClick={() => setActiveTab('demo')}
                                >
                                    Live Demo
                                </button>
                                <button
                                    className={`py-4 px-6 text-center flex-1 ${activeTab === 'features' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-600 hover:text-blue-500'}`}
                                    onClick={() => setActiveTab('features')}
                                >
                                    Features & Use Cases
                                </button>
                            </nav>
                        </div>

                        <div className="p-6 sm:p-8">
                            {activeTab === 'story' && (
                                <div className="space-y-8">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-4">The Digital Authenticity Crisis</h3>
                                        <p className="text-gray-700 leading-relaxed mb-4">
                                            In a world flooded with content—articles, social media posts, school essays, and business reports—a critical problem emerged: how do you know if something was written by a human or an AI?
                                        </p>
                                        <div className="bg-blue-50 p-4 rounded-lg border border-blue-200 my-4">
                                            <p className="text-blue-800 italic">
                                                "As AI writing tools became more sophisticated, the line between human and machine-generated content began to blur, threatening the foundation of trust in digital information."
                                            </p>
                                        </div>
                                    </section>

                                    <section>
                                        <div className="flex items-start mb-4">
                                            <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mr-4">
                                                <span className="text-blue-700 font-bold">⚙️</span>
                                            </div>
                                            <h3 className="text-2xl font-bold text-gray-900 pt-1">The Birth of AI Checker</h3>
                                        </div>
                                        <p className="text-gray-700 leading-relaxed mb-4">
                                            Enter the AI Checker, a powerful tool developed by a secretive team of engineers and linguists. Their mission was simple but critical:
                                        </p>
                                        <div className="bg-gray-800 text-blue-300 p-4 rounded-lg font-medium my-4">
                                            <p className="text-center">“To separate human creativity from machine-generated text, and preserve trust in the written word.”</p>
                                        </div>
                                        <p className="text-gray-700 leading-relaxed">
                                            Unlike ordinary grammar tools, AI Checker uses advanced machine learning models trained on thousands of AI-generated texts. It analyzes:
                                        </p>
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                                            <div className="bg-blue-50 p-4 rounded-lg">
                                                <h4 className="font-bold text-blue-700 mb-2">Text Patterns</h4>
                                                <p className="text-gray-700">AI often repeats certain structures and phrases that differ from human writing patterns.</p>
                                            </div>
                                            <div className="bg-blue-50 p-4 rounded-lg">
                                                <h4 className="font-bold text-blue-700 mb-2">Probability Distribution</h4>
                                                <p className="text-gray-700">AI uses words with predictable statistical patterns that can be detected.</p>
                                            </div>
                                            <div className="bg-blue-50 p-4 rounded-lg">
                                                <h4 className="font-bold text-blue-700 mb-2">Contextual Flow</h4>
                                                <p className="text-gray-700">Humans make subtle errors, use idioms, or have inconsistencies that AI rarely exhibits.</p>
                                            </div>
                                            <div className="bg-blue-50 p-4 rounded-lg">
                                                <h4 className="font-bold text-blue-700 mb-2">Entropy Scores</h4>
                                                <p className="text-gray-700">Measuring how "random" text is; AI tends to be unnaturally "smooth" and consistent.</p>
                                            </div>
                                        </div>
                                    </section>

                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-4">The Evolving Guardian</h3>
                                        <p className="text-gray-700 leading-relaxed">
                                            Over time, AI Checker became the guardian of digital truth: educators used it to check essays, journalists to verify sources, and companies to detect AI-written content that could harm reputation.
                                        </p>
                                        <div className="bg-blue-50 p-4 rounded-lg border border-blue-200 mt-4">
                                            <p className="text-blue-800">
                                                <span className="font-bold">Rumor has it:</span> AI Checker itself learned to anticipate AI upgrades before they were released, staying one step ahead in the AI arms race.
                                            </p>
                                        </div>
                                    </section>
                                </div>
                            )}

                            {activeTab === 'demo' && (
                                <div className="space-y-8">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-4">Try AI Checker</h3>
                                        <p className="text-gray-700 mb-6">
                                            Enter text below to analyze whether it was written by a human or AI. Our system examines patterns, word distribution, and contextual flow.
                                        </p>

                                        <div className="bg-gray-50 rounded-lg p-6 mb-6">
                                            <div className="flex items-center mb-4">
                                                <div className="flex-1">
                                                    <label htmlFor="textInput" className="block text-sm font-medium text-gray-700 mb-1">
                                                        Enter text to analyze:
                                                    </label>
                                                    <textarea
                                                        id="textInput"
                                                        className="w-full h-32 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                                        value={textInput}
                                                        onChange={(e) => setTextInput(e.target.value)}
                                                        placeholder="Paste text here to check if it's AI-generated..."
                                                    />
                                                </div>
                                            </div>

                                            <div className="flex justify-center">
                                                <button
                                                    className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-8 rounded-lg shadow-lg transition duration-300 flex items-center"
                                                    onClick={analyzeText}
                                                    disabled={isAnalyzing || textInput.length < 10}
                                                >
                                                    {isAnalyzing ? (
                                                        <>
                                                            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                                            </svg>
                                                            Analyzing...
                                                        </>
                                                    ) : (
                                                        'Analyze Text'
                                                    )}
                                                </button>
                                            </div>
                                        </div>

                                        {analysisResult && (
                                            <div className="bg-white border rounded-xl shadow-md overflow-hidden">
                                                <div className={`px-6 py-4 ${analysisResult.label === 'human' ? 'bg-green-100' : 'bg-red-100'}`}>
                                                    <div className="flex items-center">
                                                        <div className={`w-12 h-12 rounded-full flex items-center justify-center mr-4 ${analysisResult.label === 'human' ? 'bg-green-500' : 'bg-red-500'}`}>
                                                            {analysisResult.label === 'human' ? (
                                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                                </svg>
                                                            ) : (
                                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                                                </svg>
                                                            )}
                                                        </div>
                                                        <div>
                                                            <h3 className="text-xl font-bold">
                                                                {analysisResult.label === 'human' ? 'Human-written Content' : 'AI-generated Content'}
                                                            </h3>
                                                            <p className="text-gray-700">
                                                                Confidence: <span className="font-bold">{analysisResult.score * 100}%</span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div className="p-6">
                                                    <h4 className="font-bold text-gray-900 mb-4">Analysis Details</h4>
                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">Word Count</p>
                                                            <p className="text-2xl font-bold text-blue-600">{analysisResult.wordCount}</p>
                                                        </div>
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">AI Patterns Detected</p>
                                                            <p className="text-2xl font-bold text-blue-600">{analysisResult.patternsDetected}</p>
                                                        </div>
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">Entropy Score</p>
                                                            <p className="text-2xl font-bold text-blue-600">{analysisResult.entropy}</p>
                                                            <p className="text-xs text-gray-500 mt-1">(Higher = more human-like)</p>
                                                        </div>
                                                    </div>

                                                    <div className="mt-6">
                                                        <p className="font-medium text-gray-900 mb-2">How this works:</p>
                                                        <div className="bg-gray-50 p-4 rounded-lg text-sm">
                                                            <p className="mb-2">The AI Checker uses a transformer model trained on thousands of human and AI-generated texts.</p>
                                                            <p>It analyzes patterns, word distribution, and contextual flow to detect the subtle differences between human and AI writing.</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        )}

                                        {!analysisResult && (
                                            <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                                <h4 className="font-bold text-blue-800 mb-3">Example Analysis</h4>
                                                <div className="bg-white p-4 rounded-lg border border-gray-200 mb-4">
                                                    <p className="text-gray-700 mb-2">
                                                        "The sun rises in the east and sets in the west. Human creativity is infinite and unpredictable."
                                                    </p>
                                                    <div className="flex items-center">
                                                        <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center mr-3">
                                                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                            </svg>
                                                        </div>
                                                        <div>
                                                            <p className="font-bold">Human-written content</p>
                                                            <p className="text-sm text-gray-600">Confidence: 92%</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <p className="text-sm text-gray-700">
                                                    Try pasting some text from an AI writing tool or your own writing to see the difference in analysis.
                                                </p>
                                            </div>
                                        )}
                                    </section>
                                </div>
                            )}

                            {activeTab === 'features' && (
                                <div className="space-y-8">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">Key Features</h3>
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                            <div className="flex p-4 bg-blue-50 rounded-lg border border-blue-100">
                                                <div className="bg-blue-600 w-12 h-12 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2z" />
                                                    </svg>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Human vs AI Detection</h4>
                                                    <p className="text-gray-700">Accurately classifies content with a probability score indicating confidence level.</p>
                                                </div>
                                            </div>

                                            <div className="flex p-4 bg-blue-50 rounded-lg border border-blue-100">
                                                <div className="bg-blue-600 w-12 h-12 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                                    </svg>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Plagiarism & Originality Check</h4>
                                                    <p className="text-gray-700">Optional feature to detect copied AI content and ensure true originality.</p>
                                                </div>
                                            </div>

                                            <div className="flex p-4 bg-blue-50 rounded-lg border border-blue-100">
                                                <div className="bg-blue-600 w-12 h-12 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                                                    </svg>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">API Integration</h4>
                                                    <p className="text-gray-700">Seamlessly integrate into web apps, school platforms, or business tools.</p>
                                                </div>
                                            </div>

                                            <div className="flex p-4 bg-blue-50 rounded-lg border border-blue-100">
                                                <div className="bg-blue-600 w-12 h-12 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                    </svg>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Detailed Reports</h4>
                                                    <p className="text-gray-700">Comprehensive analysis of why text was flagged as AI-generated.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </section>

                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">Practical Use Cases</h3>
                                        <div className="space-y-6">
                                            <div className="flex items-start">
                                                <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <span className="text-blue-700 font-bold">🎓</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Education</h4>
                                                    <p className="text-gray-700">Teachers and professors use AI Checker to verify student essays for AI assistance, ensuring academic integrity and authentic learning.</p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <span className="text-blue-700 font-bold">📰</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Journalism</h4>
                                                    <p className="text-gray-700">Editors and news organizations verify if articles are machine-generated, maintaining trust in media and journalistic standards.</p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <span className="text-blue-700 font-bold">🏢</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Business</h4>
                                                    <p className="text-gray-700">Companies prevent AI-written spam, fake reviews, and automatically generated content that could harm reputation and customer trust.</p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                                                    <span className="text-blue-700 font-bold">✍️</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-lg text-gray-900 mb-1">Content Creation</h4>
                                                    <p className="text-gray-700">Bloggers, authors, and creators ensure originality for their work and verify the authenticity of outsourced content.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                            )}
                        </div>
                    </div>


                </div>
            </div>
        </>
    );
};

export default AIChecker;