import React, { useState, useEffect } from 'react';
import Navbar from '../../Component/Website/Header/Navbar';
import { Helmet } from "react-helmet";

const Detector = () => {
    const [inputText, setInputText] = useState('');
    const [detectionResult, setDetectionResult] = useState(null);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [activeSection, setActiveSection] = useState('story');
    const [entropyScore, setEntropyScore] = useState(0);
    const [aiProbability, setAiProbability] = useState(0);

    // Simulate text analysis
    const analyzeText = () => {
        if (inputText.trim().length < 20) return;

        setIsAnalyzing(true);
        setDetectionResult(null);

        // Simulate analysis progress
        let progress = 0;
        const progressInterval = setInterval(() => {
            progress += 5;
            setEntropyScore(Math.min(progress, 70));
            setAiProbability(Math.min(progress, 40));

            if (progress >= 100) {
                clearInterval(progressInterval);

                // Calculate mock result
                const aiPatterns = [
                    'danced under', 'soared beyond', 'it is important to note',
                    'furthermore', 'in conclusion', 'additionally', 'moreover'
                ];

                const aiPatternCount = aiPatterns.filter(pattern =>
                    inputText.toLowerCase().includes(pattern)
                ).length;

                const wordCount = inputText.split(/\s+/).length;
                const aiProbability = Math.min(0.95, (aiPatternCount / 3) + (wordCount > 100 ? 0.3 : 0.1));
                const isHuman = Math.random() > aiProbability;

                setTimeout(() => {
                    setDetectionResult({
                        label: isHuman ? 'human' : 'AI-generated',
                        confidence: (isHuman ? (0.85 + Math.random() * 0.14) : (0.90 + Math.random() * 0.09)).toFixed(2),
                        wordCount,
                        patternsDetected: aiPatternCount,
                        entropy: (3.5 + Math.random() * 1.5).toFixed(2)
                    });
                    setIsAnalyzing(false);
                }, 500);
            }
        }, 100);
    };

    return (


        <>
            <Helmet>
                {/* Primary Meta Tags */}
                <title>AI Detector: The Digital Truth Guardian</title>
                <meta
                    name="description"
                    content="Uncover the ultimate AI Detector — the tool that reveals whether text is written by a human or generated by AI. Protect originality, detect AI content, and stay ahead in the digital age."
                />
                <meta name="keywords" content="AI Detector, detect AI text, human vs AI, AI content verification, AI detection tool, machine vs human writing" />
                <meta name="robots" content="index, follow" />

                {/* Open Graph / Facebook */}
                <meta property="og:type" content="website" />
                <meta property="og:title" content="AI Detector: The Digital Truth Guardian" />
                <meta
                    property="og:description"
                    content="Discover the AI Detector — a powerful tool to identify human-written versus AI-generated content. Stay ahead in the digital age and safeguard originality."
                />
                {/* Replace with your Postimg or public folder image */}
                <meta property="og:image" content="https://i.postimg.cc/fRBN0c92/Capture-d-cran-2025-08-14-235925.png" />
                <meta property="og:url" content="https://fyrexia.co.uk/ai-detector" />

                {/* Twitter */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content="AI Detector: The Digital Truth Guardian" />
                <meta
                    name="twitter:description"
                    content="Step into the digital world with AI Detector — the ultimate tool to reveal whether text is human or AI-generated. Protect originality and detect hidden patterns."
                />
                <meta name="twitter:image" content="https://i.postimg.cc/fRBN0c92/Capture-d-cran-2025-08-14-235925.png" />
            </Helmet>
            <Navbar></Navbar>


            <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 py-12 px-4 sm:px-6 lg:px-8">
                <div className="max-w-5xl mx-auto">
                    {/* Header */}
                    <header className="text-center mb-16">
                        <div className="flex flex-col items-center">
                            <div className="w-24 h-24 bg-gradient-to-br from-blue-600 to-purple-600 rounded-full flex items-center justify-center shadow-xl mb-6">
                                <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-blue-600" viewBox="0 0 20 20" fill="currentColor">
                                        <path fillRule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 01-2 0V6H3a1 1 0 010-2h1V3a1 1 0 011-1zm0 10a1 1 0 011 1v1h1a1 1 0 110 2H6v1a1 1 0 11-2 0v-1H3a1 1 0 110-2h1v-1a1 1 0 011-1zM12 2a1 1 0 01.967.744L14.146 7.2 13.047 14.01c-.04.3-.2.575-.45.75a1.1 1.1 0 01-.847.2l-5.4-1.1a1 1 0 01-.39-.18 1.1 1.1 0 01-.3-.45L5.854 7.2 7.033 2.744A1 1 0 018 2h4zm-2 4a1 1 0 00-1 1v5a1 1 0 002 0V7a1 1 0 00-1-1zm2 9a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
                                    </svg>
                                </div>
                            </div>
                            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
                                AI Detector
                            </h1>
                            <h2 className="text-xl md:text-2xl text-gray-700 mt-3">The Digital Truth Guardian</h2>
                        </div>
                        <div className="h-1 w-48 bg-gradient-to-r from-blue-500 to-purple-500 mx-auto mt-6 rounded-full"></div>
                    </header>

                    {/* Navigation */}
                    <div className="flex flex-wrap justify-center gap-4 mb-12">
                        <button
                            className={`px-5 py-2.5 rounded-full font-medium transition-all ${activeSection === 'story' ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg' : 'bg-white text-gray-700 hover:bg-gray-100 shadow'}`}
                            onClick={() => setActiveSection('story')}
                        >
                            The Story
                        </button>
                        <button
                            className={`px-5 py-2.5 rounded-full font-medium transition-all ${activeSection === 'how' ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg' : 'bg-white text-gray-700 hover:bg-gray-100 shadow'}`}
                            onClick={() => setActiveSection('how')}
                        >
                            How It Works
                        </button>
                        <button
                            className={`px-5 py-2.5 rounded-full font-medium transition-all ${activeSection === 'demo' ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg' : 'bg-white text-gray-700 hover:bg-gray-100 shadow'}`}
                            onClick={() => setActiveSection('demo')}
                        >
                            Live Demo
                        </button>
                        <button
                            className={`px-5 py-2.5 rounded-full font-medium transition-all ${activeSection === 'applications' ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg' : 'bg-white text-gray-700 hover:bg-gray-100 shadow'}`}
                            onClick={() => setActiveSection('applications')}
                        >
                            Applications
                        </button>
                    </div>

                    {/* Content Sections */}
                    <div className="bg-white rounded-2xl shadow-xl overflow-hidden mb-16">
                        <div className="p-6 sm:p-8">
                            {/* Story Section */}
                            {activeSection === 'story' && (
                                <div className="space-y-10">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                                            <span className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-10 h-10 rounded-full flex items-center justify-center mr-4">🌌</span>
                                            The Origins
                                        </h3>
                                        <p className="text-gray-700 leading-relaxed mb-4">
                                            In the year 2025, the world was flooded with content. Articles, essays, blog posts, social media updates, and corporate reports all blurred together in a sea of words. But beneath the surface, a silent revolution was taking place. Machines were writing more than humans, and no one could tell the difference.
                                        </p>
                                        <div className="bg-gradient-to-r from-blue-50 to-purple-50 p-5 rounded-xl border border-gray-200 my-6">
                                            <p className="text-blue-800 font-medium italic">
                                                "The AI Detector began as a secret project in a small lab in Geneva, led by a team of engineers and linguists who feared the rise of undetectable AI content."
                                            </p>
                                        </div>
                                        <p className="text-gray-700 leading-relaxed mb-6">
                                            Their mission was simple but ambitious: <span className="font-semibold text-blue-700">"To preserve truth in the age of artificial intelligence."</span>
                                        </p>

                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                            <div className="bg-gradient-to-br from-blue-50 to-white p-5 rounded-xl border border-gray-200">
                                                <h4 className="font-bold text-lg text-blue-700 mb-3">Training Process</h4>
                                                <p className="text-gray-700">
                                                    The team trained the AI Detector using millions of samples from both humans and AI models, creating the most comprehensive detection system ever developed.
                                                </p>
                                            </div>
                                            <div className="bg-gradient-to-br from-purple-50 to-white p-5 rounded-xl border border-gray-200">
                                                <h4 className="font-bold text-lg text-purple-700 mb-3">Analysis Methods</h4>
                                                <ul className="text-gray-700 space-y-1">
                                                    <li className="flex items-start">
                                                        <span className="text-blue-500 mr-2">•</span>
                                                        Writing style patterns - sentence complexity, punctuation, and flow
                                                    </li>
                                                    <li className="flex items-start">
                                                        <span className="text-blue-500 mr-2">•</span>
                                                        Word probability distributions
                                                    </li>
                                                    <li className="flex items-start">
                                                        <span className="text-blue-500 mr-2">•</span>
                                                        Entropy and randomness analysis
                                                    </li>
                                                    <li className="flex items-start">
                                                        <span className="text-blue-500 mr-2">•</span>
                                                        Detection of subtle inconsistencies
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </section>

                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                                            <span className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-10 h-10 rounded-full flex items-center justify-center mr-4">⚡</span>
                                            The Breakthrough
                                        </h3>
                                        <p className="text-gray-700 leading-relaxed mb-4">
                                            After months of testing, the AI Detector became more than just a tool. It was a guardian of digital authenticity. Schools used it to check essays, journalists to verify sources, and corporations to avoid AI-written misinformation.
                                        </p>
                                        <div className="relative bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl p-6 text-white my-8 overflow-hidden">
                                            <div className="absolute top-0 right-0 opacity-20">
                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-32 w-32" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2z" />
                                                </svg>
                                            </div>
                                            <h4 className="font-bold text-xl mb-2">The Secret Weapon</h4>
                                            <p>
                                                As AI models evolved, the AI Detector learned to anticipate AI upgrades, staying one step ahead in the digital arms race. It could even detect AI-generated content from future models before they were released to the public.
                                            </p>
                                        </div>
                                    </section>

                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                                            <span className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-10 h-10 rounded-full flex items-center justify-center mr-4">⚠️</span>
                                            The Hidden Legend
                                        </h3>
                                        <p className="text-gray-700 leading-relaxed">
                                            Rumors spread among digital communities: the AI Detector is self-learning, capable of detecting AI content it has never seen before. Some believe it could even identify the authors behind AI scripts based on subtle writing fingerprints.
                                        </p>
                                        <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-6 rounded-xl text-white mt-6">
                                            <p className="text-center text-lg font-medium">
                                                In a world where machines write faster than humans, AI Detector became the last line of defense—the guardian of truth, creativity, and originality.
                                            </p>
                                        </div>
                                    </section>
                                </div>
                            )}

                            {/* How It Works Section */}
                            {activeSection === 'how' && (
                                <div className="space-y-10">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">The Detection Process</h3>
                                        <p className="text-gray-700 mb-6">
                                            AI Detector uses advanced algorithms to analyze text through multiple stages of examination. Here's how it identifies machine-generated content:
                                        </p>

                                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                            <div className="bg-gradient-to-b from-blue-50 to-white p-5 rounded-xl border border-gray-200">
                                                <div className="text-blue-600 text-3xl mb-3">1</div>
                                                <h4 className="font-bold text-lg text-gray-900 mb-2">Tokenization</h4>
                                                <p className="text-gray-700">
                                                    The text is split into individual words, phrases, and sentences for detailed analysis.
                                                </p>
                                            </div>
                                            <div className="bg-gradient-to-b from-purple-50 to-white p-5 rounded-xl border border-gray-200">
                                                <div className="text-purple-600 text-3xl mb-3">2</div>
                                                <h4 className="font-bold text-lg text-gray-900 mb-2">Feature Extraction</h4>
                                                <p className="text-gray-700">
                                                    The system examines sentence structure, word patterns, and stylistic elements.
                                                </p>
                                            </div>
                                            <div className="bg-gradient-to-b from-blue-100 to-white p-5 rounded-xl border border-gray-200">
                                                <div className="text-blue-700 text-3xl mb-3">3</div>
                                                <h4 className="font-bold text-lg text-gray-900 mb-2">Pattern Recognition</h4>
                                                <p className="text-gray-700">
                                                    Machine learning models identify statistical patterns characteristic of AI systems.
                                                </p>
                                            </div>
                                        </div>

                                        <div className="bg-gray-50 rounded-xl p-6 mb-8">
                                            <h4 className="font-bold text-lg text-gray-900 mb-4">Example Analysis</h4>
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                                <div>
                                                    <p className="text-gray-700 mb-2">Input text:</p>
                                                    <div className="bg-white p-4 rounded-lg border border-gray-300 shadow-sm">
                                                        <p className="text-gray-700 italic">
                                                            "The ocean waves danced under the moonlight, while human imagination soared beyond the stars."
                                                        </p>
                                                    </div>
                                                </div>
                                                <div>
                                                    <p className="text-gray-700 mb-2">Analysis result:</p>
                                                    <div className="bg-green-100 p-4 rounded-lg border border-green-300">
                                                        <div className="flex items-center">
                                                            <div className="w-10 h-10 bg-green-500 rounded-full flex items-center justify-center mr-3">
                                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                                </svg>
                                                            </div>
                                                            <div>
                                                                <p className="font-bold text-gray-900">Human-written</p>
                                                                <p className="text-gray-700">Confidence: 95%</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6">
                                            <h4 className="font-bold text-lg text-gray-900 mb-4">Technical Implementation</h4>
                                            <pre className="bg-gray-800 text-green-400 p-4 rounded-lg overflow-x-auto text-sm">
                                                {`from transformers import pipeline

# Load a model trained for AI detection
detector = pipeline("text-classification", 
                   model="roberta-base-openai-detector")

text = "The ocean waves danced under the moonlight, 
        while human imagination soared beyond the stars."

result = detector(text)

print(result)
# Output: [{'label': 'human', 'score': 0.95}]`}
                                            </pre>
                                        </div>
                                    </section>
                                </div>
                            )}

                            {/* Live Demo Section */}
                            {activeSection === 'demo' && (
                                <div className="space-y-8">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">AI Detection Demo</h3>
                                        <p className="text-gray-700 mb-6">
                                            Enter text below to analyze whether it was written by a human or AI. Our system examines patterns, word distribution, and contextual flow.
                                        </p>

                                        <div className="bg-gray-50 rounded-xl p-6 mb-6">
                                            <div className="mb-6">
                                                <label htmlFor="textInput" className="block text-sm font-medium text-gray-700 mb-2">
                                                    Enter text to analyze:
                                                </label>
                                                <textarea
                                                    id="textInput"
                                                    className="w-full h-40 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                                    value={inputText}
                                                    onChange={(e) => setInputText(e.target.value)}
                                                    placeholder="Paste text here to check if it's AI-generated..."
                                                />
                                            </div>

                                            <div className="flex justify-center">
                                                <button
                                                    className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-medium py-3 px-8 rounded-lg shadow-lg transition-all duration-300 flex items-center disabled:opacity-50"
                                                    onClick={analyzeText}
                                                    disabled={isAnalyzing || inputText.length < 20}
                                                >
                                                    {isAnalyzing ? (
                                                        <>
                                                            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                                            </svg>
                                                            Analyzing...
                                                        </>
                                                    ) : (
                                                        'Analyze Text'
                                                    )}
                                                </button>
                                            </div>
                                        </div>

                                        {isAnalyzing && (
                                            <div className="bg-white border rounded-xl shadow-md p-6">
                                                <h4 className="font-bold text-gray-900 mb-4">Analysis in Progress</h4>
                                                <div className="space-y-4">
                                                    <div>
                                                        <div className="flex justify-between mb-1">
                                                            <span className="text-sm font-medium text-blue-700">Entropy Score</span>
                                                            <span className="text-sm font-medium text-blue-700">{entropyScore}%</span>
                                                        </div>
                                                        <div className="w-full bg-gray-200 rounded-full h-2.5">
                                                            <div className="bg-blue-600 h-2.5 rounded-full" style={{ width: `${entropyScore}%` }}></div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div className="flex justify-between mb-1">
                                                            <span className="text-sm font-medium text-purple-700">AI Probability</span>
                                                            <span className="text-sm font-medium text-purple-700">{aiProbability}%</span>
                                                        </div>
                                                        <div className="w-full bg-gray-200 rounded-full h-2.5">
                                                            <div className="bg-purple-600 h-2.5 rounded-full" style={{ width: `${aiProbability}%` }}></div>
                                                        </div>
                                                    </div>
                                                    <div className="text-center text-gray-500 mt-4">
                                                        Scanning for AI patterns and anomalies...
                                                    </div>
                                                </div>
                                            </div>
                                        )}

                                        {detectionResult && (
                                            <div className="bg-white border rounded-xl shadow-md overflow-hidden">
                                                <div className={`px-6 py-4 ${detectionResult.label === 'human' ? 'bg-green-100' : 'bg-red-100'}`}>
                                                    <div className="flex items-center">
                                                        <div className={`w-12 h-12 rounded-full flex items-center justify-center mr-4 ${detectionResult.label === 'human' ? 'bg-green-500' : 'bg-red-500'}`}>
                                                            {detectionResult.label === 'human' ? (
                                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                                </svg>
                                                            ) : (
                                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                                                </svg>
                                                            )}
                                                        </div>
                                                        <div>
                                                            <h3 className="text-xl font-bold">
                                                                {detectionResult.label === 'human' ? 'Human-written Content' : 'AI-generated Content'}
                                                            </h3>
                                                            <p className="text-gray-700">
                                                                Confidence: <span className="font-bold">{detectionResult.confidence * 100}%</span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div className="p-6">
                                                    <h4 className="font-bold text-gray-900 mb-4">Analysis Details</h4>
                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">Word Count</p>
                                                            <p className="text-2xl font-bold text-blue-600">{detectionResult.wordCount}</p>
                                                        </div>
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">AI Patterns Detected</p>
                                                            <p className="text-2xl font-bold text-blue-600">{detectionResult.patternsDetected}</p>
                                                        </div>
                                                        <div className="border border-gray-200 rounded-lg p-4">
                                                            <p className="text-sm text-gray-600">Entropy Score</p>
                                                            <p className="text-2xl font-bold text-blue-600">{detectionResult.entropy}</p>
                                                            <p className="text-xs text-gray-500 mt-1">(Higher = more human-like)</p>
                                                        </div>
                                                    </div>

                                                    <div className="mt-6">
                                                        <p className="font-medium text-gray-900 mb-2">Interpretation:</p>
                                                        <div className="bg-gray-50 p-4 rounded-lg text-sm">
                                                            {detectionResult.label === 'human' ? (
                                                                <p>This text shows characteristics of human writing including varied sentence structures, natural inconsistencies, and higher entropy that is difficult for AI models to replicate.</p>
                                                            ) : (
                                                                <p>This text exhibits patterns consistent with AI generation, including predictable word choices, repetitive structures, and statistically probable word sequences that differ from human writing patterns.</p>
                                                            )}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        )}
                                    </section>
                                </div>
                            )}

                            {/* Applications Section */}
                            {activeSection === 'applications' && (
                                <div className="space-y-10">
                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">Real-World Applications</h3>
                                        <p className="text-gray-700 mb-8">
                                            AI Detector has become an essential tool across multiple industries, helping maintain authenticity and trust in digital content.
                                        </p>

                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                            <div className="flex items-start">
                                                <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-14 h-14 rounded-xl flex items-center justify-center mr-5 flex-shrink-0">
                                                    <span className="text-2xl">🎓</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-xl text-gray-900 mb-2">Education</h4>
                                                    <p className="text-gray-700">
                                                        Teachers and professors use AI Detector to verify student essays, ensuring academic integrity and authentic learning experiences.
                                                    </p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-14 h-14 rounded-xl flex items-center justify-center mr-5 flex-shrink-0">
                                                    <span className="text-2xl">📰</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-xl text-gray-900 mb-2">Journalism</h4>
                                                    <p className="text-gray-700">
                                                        News organizations verify the authenticity of articles and sources, maintaining trust in media and journalistic standards.
                                                    </p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-14 h-14 rounded-xl flex items-center justify-center mr-5 flex-shrink-0">
                                                    <span className="text-2xl">🏢</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-xl text-gray-900 mb-2">Corporate Security</h4>
                                                    <p className="text-gray-700">
                                                        Companies detect AI-written spam, fake reviews, and automatically generated content that could harm reputation and customer trust.
                                                    </p>
                                                </div>
                                            </div>

                                            <div className="flex items-start">
                                                <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white w-14 h-14 rounded-xl flex items-center justify-center mr-5 flex-shrink-0">
                                                    <span className="text-2xl">✍️</span>
                                                </div>
                                                <div>
                                                    <h4 className="font-bold text-xl text-gray-900 mb-2">Content Creation</h4>
                                                    <p className="text-gray-700">
                                                        Writers, bloggers, and creators ensure originality for their work and verify the authenticity of outsourced content.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </section>

                                    <section>
                                        <h3 className="text-2xl font-bold text-gray-900 mb-6">The Future of Authenticity</h3>
                                        <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6 border border-gray-200">
                                            <p className="text-gray-700 mb-4">
                                                As AI writing tools become increasingly sophisticated, the role of AI Detector evolves to meet new challenges:
                                            </p>
                                            <ul className="space-y-3">
                                                <li className="flex items-start">
                                                    <div className="bg-blue-600 w-6 h-6 rounded-full flex items-center justify-center mr-3 mt-1 flex-shrink-0">
                                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" viewBox="0 0 20 20" fill="currentColor">
                                                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                                                        </svg>
                                                    </div>
                                                    <span className="text-gray-700">Detection of hybrid human-AI content</span>
                                                </li>
                                                <li className="flex items-start">
                                                    <div className="bg-blue-600 w-6 h-6 rounded-full flex items-center justify-center mr-3 mt-1 flex-shrink-0">
                                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" viewBox="0 0 20 20" fill="currentColor">
                                                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                                                        </svg>
                                                    </div>
                                                    <span className="text-gray-700">Identification of specific AI models used</span>
                                                </li>
                                                <li className="flex items-start">
                                                    <div className="bg-blue-600 w-6 h-6 rounded-full flex items-center justify-center mr-3 mt-1 flex-shrink-0">
                                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" viewBox="0 0 20 20" fill="currentColor">
                                                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                                                        </svg>
                                                    </div>
                                                    <span className="text-gray-700">Real-time detection in communication platforms</span>
                                                </li>
                                                <li className="flex items-start">
                                                    <div className="bg-blue-600 w-6 h-6 rounded-full flex items-center justify-center mr-3 mt-1 flex-shrink-0">
                                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" viewBox="0 0 20 20" fill="currentColor">
                                                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                                                        </svg>
                                                    </div>
                                                    <span className="text-gray-700">Blockchain verification of human authorship</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </section>
                                </div>
                            )}
                        </div>
                    </div>

                </div>
            </div>
        </>
    );
};

export default Detector;